title: Dohlothek
description: Willkommen in der Dohlothek! Hier kannst du freiwillig Gartengeräte und andere nützliche Dinge mit deinen Nachbarn teilen, um Ressourcen zu sparen und um andere zu untertsützen! Hier läuft alles persönlich und unkompliziert ab: Klingel einfach bei deinem Nachbarn, um etwas auszuleihen oder zu verleihen. Sei dabei und genieße die Vorteile einer nachhaltigen Nachbarschaft!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
